baseurl: /core-values-draft
markdown: redcarpet
name: 18F Core Values [DRAFT]
description: >
  Statement of 18F core values that inform our culture and working models

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Intro
  url: index.html
  internal: true
- text: Making Government Work Better
  url: making-government-work-better/
  internal: true
- text: Transparency
  url: transparency/
  internal: true
- text: Integrity
  url: integrity/
  internal: true
- text: Shared Responsibility
  url: shared-responsibility/
  internal: true
- text: Shipping
  url: shipping/
  internal: true
- text: Autonomy
  url: autonomy/
  internal: true

repos:
- name: 18F Core Values
  description: Main repository
  url: https://github.com/18F/core-values

# Style Variables
brand_color: "#1188ff"
